/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 shelf.gltf --transform --shadows --keepmaterials --keepmeshes --keepnames 
Files: shelf.gltf [21.34KB] > C:\Users\abhishek\Desktop\three-fiber-main\droneTask\public\shelf-transformed.glb [14.7KB] (31%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Shelf(props) {
  const { nodes, materials } = useGLTF("/shelf-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube033.geometry}
          material={materials["BrownDark.049"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube033_1.geometry}
          material={materials["PurpleDark.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube033_2.geometry}
          material={materials["White.034"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube033_3.geometry}
          material={materials["Metal.080"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube033_4.geometry}
          material={materials["BlueDark.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube033_5.geometry}
          material={materials["GreenDark.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube033_6.geometry}
          material={materials["WoodDark.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube033_7.geometry}
          material={materials["StoneDark.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube033_8.geometry}
          material={materials["Black.030"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/shelf-transformed.glb");
