/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 tesla.gltf --transform --shadows --keepmaterials --keepmeshes --keepnames 
Files: tesla.gltf [1.14MB] > C:\Users\abhishek\Desktop\three-fiber-main\droneTask\public\tesla-transformed.glb [66.26KB] (94%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Tesla(props) {
  const { nodes, materials } = useGLTF("/tesla-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tires.geometry}
        material={materials["rubber.002"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.interior003.geometry}
        material={materials["light_f.002"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.interior003_1.geometry}
        material={materials["body.002"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.interior003_2.geometry}
        material={materials.glass_crack}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.interior003_3.geometry}
        material={materials.Light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.interior003_4.geometry}
        material={materials["gray.002"]}
      />
    </group>
  );
}

useGLTF.preload("/tesla-transformed.glb");
